CREATE TABLE IF NOT EXISTS `#__sportowiada_disciplines` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `created_by` INT(11) UNSIGNED DEFAULT NULL,
  `modified` DATETIME DEFAULT NULL,
  `modified_by` INT(11) UNSIGNED DEFAULT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
